In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
calorie = pd.read_csv("calories.csv")
exercise = pd.read_csv("exercise.csv")

In [3]:
calorie.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   User_ID   15000 non-null  int64  
 1   Calories  15000 non-null  float64
dtypes: float64(1), int64(1)
memory usage: 234.5 KB


In [4]:
calorie.head()

User_ID  Calories
0  14733363     231.0
1  14861698      66.0
2  11179863      26.0
3  16180408      71.0
4  17771927      35.0

In [5]:
calorie.describe()

User_ID      Calories
count  1.500000e+04  15000.000000
mean   1.497736e+07     89.539533
std    2.872851e+06     62.456978
min    1.000116e+07      1.000000
25%    1.247419e+07     35.000000
50%    1.499728e+07     79.000000
75%    1.744928e+07    138.000000
max    1.999965e+07    314.000000

In [6]:
exercise.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   User_ID     15000 non-null  int64  
 1   Gender      15000 non-null  object 
 2   Age         15000 non-null  int64  
 3   Height      15000 non-null  float64
 4   Weight      15000 non-null  float64
 5   Duration    15000 non-null  float64
 6   Heart_Rate  15000 non-null  float64
 7   Body_Temp   15000 non-null  float64
dtypes: float64(5), int64(2), object(1)
memory usage: 937.6+ KB


In [7]:
exercise.head()

User_ID  Gender  Age  Height  Weight  Duration  Heart_Rate  Body_Temp
0  14733363    male   68   190.0    94.0      29.0       105.0       40.8
1  14861698  female   20   166.0    60.0      14.0        94.0       40.3
2  11179863    male   69   179.0    79.0       5.0        88.0       38.7
3  16180408  female   34   179.0    71.0      13.0       100.0       40.5
4  17771927  female   27   154.0    58.0      10.0        81.0       39.8

In [8]:
exercise.describe()

User_ID           Age        Height        Weight      Duration  \
count  1.500000e+04  15000.000000  15000.000000  15000.000000  15000.000000   
mean   1.497736e+07     42.789800    174.465133     74.966867     15.530600   
std    2.872851e+06     16.980264     14.258114     15.035657      8.319203   
min    1.000116e+07     20.000000    123.000000     36.000000      1.000000   
25%    1.247419e+07     28.000000    164.000000     63.000000      8.000000   
50%    1.499728e+07     39.000000    175.000000     74.000000     16.000000   
75%    1.744928e+07     56.000000    185.000000     87.000000     23.000000   
max    1.999965e+07     79.000000    222.000000    132.000000     30.000000   

         Heart_Rate     Body_Temp  
count  15000.000000  15000.000000  
mean      95.518533     40.025453  
std        9.583328      0.779230  
min       67.000000     37.100000  
25%       88.000000     39.600000  
50%       96.000000     40.200000  
75%      103.000000     40.600000  
max      128.000000     41.500000

In [9]:
exercise.isnull().sum()

User_ID       0
Gender        0
Age           0
Height        0
Weight        0
Duration      0
Heart_Rate    0
Body_Temp     0
dtype: int64

In [10]:
df = pd.merge(exercise,calorie,how='left',on = 'User_ID')

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   User_ID     15000 non-null  int64  
 1   Gender      15000 non-null  object 
 2   Age         15000 non-null  int64  
 3   Height      15000 non-null  float64
 4   Weight      15000 non-null  float64
 5   Duration    15000 non-null  float64
 6   Heart_Rate  15000 non-null  float64
 7   Body_Temp   15000 non-null  float64
 8   Calories    15000 non-null  float64
dtypes: float64(6), int64(2), object(1)
memory usage: 1.0+ MB


In [12]:
df.head()

User_ID  Gender  Age  Height  Weight  Duration  Heart_Rate  Body_Temp  \
0  14733363    male   68   190.0    94.0      29.0       105.0       40.8   
1  14861698  female   20   166.0    60.0      14.0        94.0       40.3   
2  11179863    male   69   179.0    79.0       5.0        88.0       38.7   
3  16180408  female   34   179.0    71.0      13.0       100.0       40.5   
4  17771927  female   27   154.0    58.0      10.0        81.0       39.8   

   Calories  
0     231.0  
1      66.0  
2      26.0  
3      71.0  
4      35.0

In [13]:
X = df.drop(['User_ID','Calories'],axis=1)

In [14]:
X.values

array([['male', 68, 190.0, ..., 29.0, 105.0, 40.8],
       ['female', 20, 166.0, ..., 14.0, 94.0, 40.3],
       ['male', 69, 179.0, ..., 5.0, 88.0, 38.7],
       ...,
       ['female', 43, 159.0, ..., 16.0, 90.0, 40.1],
       ['male', 78, 193.0, ..., 2.0, 84.0, 38.3],
       ['male', 63, 173.0, ..., 18.0, 92.0, 40.5]], dtype=object)

In [15]:
y = df['Calories']

In [16]:
y.shape

(15000,)

In [17]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [18]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder = 'passthrough')

In [19]:
X = ct.fit_transform(X)

In [20]:
X

array([[  0. ,   1. ,  68. , ...,  29. , 105. ,  40.8],
       [  1. ,   0. ,  20. , ...,  14. ,  94. ,  40.3],
       [  0. ,   1. ,  69. , ...,   5. ,  88. ,  38.7],
       ...,
       [  1. ,   0. ,  43. , ...,  16. ,  90. ,  40.1],
       [  0. ,   1. ,  78. , ...,   2. ,  84. ,  38.3],
       [  0. ,   1. ,  63. , ...,  18. ,  92. ,  40.5]])

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [23]:
X_train

array([[  0. ,   1. ,  78. , ...,   8. ,  95. ,  39.5],
       [  1. ,   0. ,  54. , ...,   9. ,  92. ,  39.9],
       [  1. ,   0. ,  23. , ...,  17. ,  88. ,  40.1],
       ...,
       [  1. ,   0. ,  36. , ...,  22. , 106. ,  40.6],
       [  1. ,   0. ,  56. , ...,  13. ,  94. ,  39.9],
       [  0. ,   1. ,  28. , ...,   2. ,  72. ,  38. ]])

In [24]:
y_train

13136     57.0
3536      47.0
10296     67.0
2137      35.0
14775     25.0
         ...  
13123    175.0
3264       5.0
9845     137.0
10799     69.0
2732       1.0
Name: Calories, Length: 12000, dtype: float64

In [25]:
from xgboost import XGBRegressor

In [26]:
model = XGBRegressor()

In [27]:
model.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=None, n_jobs=None,
             num_parallel_tree=None, random_state=None, ...)

In [28]:
predict = model.predict(X_test)

In [29]:
predict

array([ 42.158726,  16.409174,  99.261345, ...,  26.832329, 148.18468 ,
       153.74557 ], dtype=float32)

In [30]:
y_test

1670      43.0
13379     15.0
10234    101.0
4719     186.0
7003     126.0
         ...  
10346     88.0
8469     145.0
12765     29.0
9431     150.0
4202     157.0
Name: Calories, Length: 3000, dtype: float64

In [31]:
from sklearn import metrics

In [32]:
mae = metrics.mean_absolute_error(y_test,predict)

In [33]:
print("Mean Absolute Error = ",mae)

Mean Absolute Error =  1.5211099035541216


In [34]:
y_min = 1
y_max = 314
mae = 1.5211099035541216

# Calculate the percentage of the target variable range
percentage_error = (mae / (y_max - y_min)) * 100
print(f"MAE as a percentage of the target variable range: {percentage_error:.2f}%")

MAE as a percentage of the target variable range: 0.49%
